
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: Default

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: AIOTests@0
  inputs:
    jiraHosting: 'cloud'
    cloudAuth: 'NTFiMmVlYzQtOTNhMi0zMTkyLTk1MTYtMjZlMmZlNjQ3ZjAxLjQ3YWNmMThiLTk1ZmQtNDdjOC1hMzkxLTAzNTJlNWRkMWY1Mw=='
    projectKey: 'TSP'
    cylePreferences: 'newCycle'
    cycleTitle: 'AZURE'
    batchImport: true
    frameworkOptions: 'cucumber'
    resultsFilePath: '/Users/ASUS/Downloads/vsts-agent-win-x64-4.255.0/_work/1/s/target/cucumber-reports/Cucumber_Login.json'
    createNewRun: true
    addCaseToCycle: true
    defaultFolder: 'AZURE'
    updateOnlyRunStatus: true
